<h2> Function Mapping </h2>


In [3]:
import math
radii = [2,3,7,25, 50]

In [8]:
def area (r):
    return math.pi *r **2

<h6>  list (map(<span style="color:blue;">functionName</span>, <span style="color:blue"> listName </span>)) </h6>

In [9]:
list(map(area , radii))

[12.566370614359172,
 28.274333882308138,
 153.93804002589985,
 1963.4954084936207,
 7853.981633974483]

<p> map this QUAD function on power list 

In [15]:
powerlist = [-8,-6-4, -2, 0 , 2, 4, 6, 8]

In [17]:
def quad(x):
    return x**2 + 5*x +6
    

In [19]:
list(map( quad, powerlist))

[30, 56, 0, 6, 20, 42, 72, 110]

<p>now map this Detailed list with tuples

In [24]:
def quadD(x):
    return ( x**2 , 5*x , 6, x**2+5*x +6)

In [25]:
list(map( quadD, powerlist))

[(64, -40, 6, 30),
 (100, -50, 6, 56),
 (4, -10, 6, 0),
 (0, 0, 6, 6),
 (4, 10, 6, 20),
 (16, 20, 6, 42),
 (36, 30, 6, 72),
 (64, 40, 6, 110)]

<h2> List Comprehension </h2>

In [31]:
compr = [x * 3 for x in range (2,10)]
compr

[6, 9, 12, 15, 18, 21, 24, 27]

<p> [ <span style=color:blue >  expression   </span> for  <span style=color:blue > item in list   </span>  ]

In [35]:
compr = [x * 3 for x in range (2,10) if x % 2 ==0]
compr

[6, 12, 18, 24]

<p> [ <span style=color:blue >  expression   </span> for  <span style=color:blue > item in list    conditional</span>  ]

<p> define comprPower x ^2  for 10 to 100 each 10

In [42]:
comprPower = [x ** 2 for x in range(10,101,10)]
comprPower

[100, 400, 900, 1600, 2500, 3600, 4900, 6400, 8100, 10000]

<h2>  summary of 'auto arrays ' incl numpy </h2>

In [48]:
myarange = [x for x in range(1,10,3)]
myarange

[1, 4, 7]

In [50]:
import numpy as np
mynparange= np.arange(1,10,3)
mynparange

array([1, 4, 7])

<p> np.arange / range (<span style=color:blue >  start   </span> , 
    <span style=color:blue >  stop   </span>, 
    <span style=color:blue >  step   </span>)

In [53]:
mylinspace = np.linspace(0,10,3)
mylinspace

array([ 0.,  5., 10.])

<p> linspace (<span style=color:blue >  start   </span> , 
    <span style=color:blue >  stop   </span>, 
    <span style=color:blue > numbers   </span>)

In [76]:
degs=np.arange(0,362, 15)
degs

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180,
       195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360])

In [77]:
np.round(np.sin(np.deg2rad(degs)),3)

array([ 0.   ,  0.259,  0.5  ,  0.707,  0.866,  0.966,  1.   ,  0.966,
        0.866,  0.707,  0.5  ,  0.259,  0.   , -0.259, -0.5  , -0.707,
       -0.866, -0.966, -1.   , -0.966, -0.866, -0.707, -0.5  , -0.259,
       -0.   ])

In [78]:
1-0.269

0.731