<h1>Neural Network Basics </h1>

<h2>  a Forward Propagation Model from scratch </h2>

<ul> <li> intro</li>
    <li>Initialize a Network</li>
        <li>Compute  Weighted Sum at Each Node</li>
    
    <li> Compute Node  Activation </li>
    <li> Forward Propagation</li>
</ul>

<a href ="https://labs.cognitiveclass.ai/tools/jupyterlab/lab/tree/labs/DL0101EN/DL0101EN-3-1-Regression-with-Keras-py-v1.0.ipynb">link </a>

<h3>intro </h3>

<img src="http://cocl.us/neural_network_example" alt="Neural Network Example" width=600px>

In [1]:
import numpy as np

initialize the weights and biases as numpy arrays on `random.uniform()` distribution

In [2]:
weights = np.around(np.random.uniform(size=6), decimals=2) # initialize the weights
biases = np.around(np.random.uniform(size=3), decimals=2) # initialize the biases
print(weights)
print(biases)

[0.77 0.17 0.9  0.54 0.58 0.99]
[0.59 0.58 0.9 ]


Now that we have the weights and the biases defined for the network, let's compute the output for a given input, $x_1$ and $x_2$.

In [3]:
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

print('x1 is {} and x2 is {}'.format(x_1, x_2))

x1 is 0.5 and x2 is 0.85


computing the **weighted sum of the inputs**, 𝑧1,1, at the first node of the hidden layer.

In [4]:
z_11 = x_1 * weights[0] + x_2 * weights[1] + biases[0]
z_11

1.1195

<p> <span style="color:purple"> compute the weighted sum of Z_12</span>

In [5]:
z_12 = x_1 * weights[2] + + x_2 * weights[3] +biases[1]
z_12

1.4889999999999999

sigmoid activation of the first node

In [6]:
a_11 = 1.0 / (1.0 + np.exp(-z_11))

<p> <span style="color:purple"> compute the sigmoid for a_12</span>

In [9]:
a_12 = 1.0 /(1.0 + np.exp(-z_12))
a_12

0.8159281306107906

These **activations** are **inputs** for the  **output layer**
assign the 

In [10]:
z_2 = a_11 * weights[4] +a_12 * weights[5] + biases[2]
z_2

2.1450285059917866

<p> <span style="color:purple"> compute the sigmoid a_2 for z_2 </span>

In [12]:
a_2 = 1.0 / (1.0 + np.exp(-z_2))
a_2

0.8952032948885565

<h3>Initialize a Network </h3>


`n` number of inputs <br>
`num_hidden_layers` number of hidden layers<br>
`m` (list) of len=num _hidden layers nuber of nodes in each hidden layer <br>
`num_nodes_output` number of node in the output layer

In [15]:
#structure of a network
n = 2 # number of inputs
num_hidden_layers = 2 # number of hidden layers
m = [2, 2] # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer

<h4> inititailize the weights and the biases in the network to random numbers </h4>



In [16]:
import numpy as np # import the Numpy library

num_nodes_previous = n # number of nodes in the previous layer

network = {} # initialize network an an empty dictionary

# loop through each layer and randomly initialize the weights and biases associated with each node
# notice how we are adding 1 to the number of hidden layers in order to include the output layer
for layer in range(num_hidden_layers + 1): 
    
    # determine name of layer
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
    
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network

{'layer_1': {'node_1': {'weights': array([0.08, 0.49]), 'bias': array([0.45])}, 'node_2': {'weights': array([0.73, 0.07]), 'bias': array([0.71])}}, 'layer_2': {'node_1': {'weights': array([0.96, 0.38]), 'bias': array([0.01])}, 'node_2': {'weights': array([0.38, 0.75]), 'bias': array([0.21])}}, 'output': {'node_1': {'weights': array([0.05, 0.8 ]), 'bias': array([0.09])}}}


<h4>The code in a function </h4>

In [24]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network
  

with `initialize_network()` create a network with
n=5 inputs, 3 hidden layers, nodes in layers as 3 in 1st, 2 in 2nd 3  in 3rd, 1 input layer

In [27]:
small_network = initialize_network( 5 , 3 , [3,2,3],1)
small_network

{'layer_1': {'node_1': {'weights': array([0.97, 0.6 , 0.47, 0.58, 0.52]),
   'bias': array([0.67])},
  'node_2': {'weights': array([0.11, 0.17, 0.15, 0.71, 0.33]),
   'bias': array([0.83])},
  'node_3': {'weights': array([0.06, 0.92, 0.09, 0.3 , 0.4 ]),
   'bias': array([0.2])}},
 'layer_2': {'node_1': {'weights': array([0.85, 0.93, 0.81]),
   'bias': array([0.95])},
  'node_2': {'weights': array([0.45, 0.22, 0.56]), 'bias': array([0.03])}},
 'layer_3': {'node_1': {'weights': array([0.28, 0.45]), 'bias': array([0.55])},
  'node_2': {'weights': array([0.24, 0.17]), 'bias': array([0.67])},
  'node_3': {'weights': array([0.59, 0.24]), 'bias': array([0.6])}},
 'output': {'node_1': {'weights': array([0.13, 0.84, 0.22]),
   'bias': array([0.51])}}}

<h3> Compute the Weighted sum at each node </h3>


the function will receive arguments inputs, weights and bias

In [28]:
def compute_weighted_sum (inputs, weights, bias):
    return np.sum(inputs * weights) + bias

generate the 5 inputs to feed the **small network**

In [30]:
from random import seed
import numpy as np
np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)
inputs

array([0.15, 0.74, 0.26, 0.53, 0.01])

<p> <span style="color:purple"> use the `compute_weighted_sum` function to compute the weighted sum of the first node in the first layer  </span>

In [31]:
node_weights = small_network['layer_1']['node_1']['weights']
node_bias =    small_network['layer_1']['node_1']['bias']
weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
result=np.around(weighted_sum[0], decimals=4)
result
weighted_sum

array([1.6943])

<h3> Compute Node Activation </h3>

In [32]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

<p> <span style="color:purple"> use the `node_activation_function` to compute the output of the first node in the first hidden layer. assign to `node_output` </span>

In [34]:
node_output = node_activation( compute_weighted_sum(inputs, node_weights, node_bias))


<h3>Forward Propagation </h3>

1. Start with the input layer as the input to the first hidden layer.
2. Compute the weighted sum at the nodes of the current layer.
3. Compute the output of the nodes of the current layer.
4. Set the output of the current layer to be the input to the next layer.
5. Move to the next layer in the network.
5. Repeat steps 2 - 4 until we compute the output of the output layer.

In [36]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

<p> <span style="color:purple">with the function compute the prediction of the small network </span>

In [37]:
### type your answser here
predictions = forward_propagate(small_network, inputs)
predictions

The outputs of the nodes in hidden layer number 1 is [0.8448, 0.8007, 0.7458]
The outputs of the nodes in hidden layer number 2 is [0.9533, 0.7318]
The outputs of the nodes in hidden layer number 3 is [0.7588, 0.7356, 0.7922]


[0.8023]

use the  `initialize_network()` to create our neural network and define its weights and biases.

In [38]:
my_network = initialize_network(5, 3, [2, 3, 2], 3)

for  given inputs

In [39]:
inputs = np.around(np.random.uniform(size=5), decimals=2)
inputs

array([0.96, 0.42, 0.42, 0.46, 0.37])

compute predictions

In [40]:
predictions = forward_propagate(my_network, inputs)
print('The predicted values by the network for the given input are {}'.format(predictions))

The outputs of the nodes in hidden layer number 1 is [0.8857, 0.8889]
The outputs of the nodes in hidden layer number 2 is [0.7822, 0.6965, 0.7411]
The outputs of the nodes in hidden layer number 3 is [0.868, 0.881]
The predicted values by the network for the given input are [0.8952, 0.8222, 0.8035]
