<h1> Vectors and Matrices - numpy </h1>

In [24]:
import numpy as np

<h2>Dense and Sparse 
Matrix Storage</h2>

<h3> linearize(): return the index for a col or row-major matrix</h3> 

`linearize___(i,j,m,n):`

In [1]:
def linearize_colmajor(i, j, m, n): # calculate `u`
    """
    Returns the linear index for the `(i, j)` entry of
    an `m`-by-`n` matrix stored in column-major order.
    """
    return i + j*m

In [20]:
def linearize_rowmajor(i, j, m, n): # calculate `v`
    """
    Returns the linear index for the `(i, j)` entry of
    an `m`-by-`n` matrix stored in row-major order.
    """
    return i*n + j

example for a 3 * 4 matrix <br>
`m=3
n=4`

In [23]:
m=3
n=4
cell1=(0,3)
cell2=(1,2)
print("for an {:} by {:} matrix".format(m,n))
print("representing cell 1: {:}".format(cell1))
print("colmajor: "+str(linearize_colmajor(cell1[0], cell1[1],m,n)))
print("rowmajor: "+str(linearize_rowmajor(cell1[0], cell1[1],m,n)))
print("representing cell 2: {:}".format(cell2))
print("colmajor: "+str(linearize_colmajor(cell2[0], cell2[1],m,n)))
print("rowmajor: "+str(linearize_rowmajor(cell2[0], cell2[1],m,n)))


for an 3 by 4 matrix
representing cell 1: (0, 3)
colmajor: 9
rowmajor: 3
representing cell 2: (1, 2)
colmajor: 7
rowmajor: 6


In [57]:
A=np.arange(0,12)
A=A.reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
A[2][3]=99
A

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 99]])

implementing a column major function

In [63]:
def colmaj(A):
    LinA = np.ones(A.shape[0]*A.shape[1])

    for j in range(A.shape[1]):
        for i in range( A.shape[0]):
           # print (A[j*A.shape[0] * i])
            LinA[j*A.shape[0]+i] = A[i][j]
        
    return LinA
print(colmaj(A))

[ 0.  4.  8.  1.  5.  9.  2.  6. 10.  3.  7. 99.]


<h4> Numpy leyouts for colmaj and rowmaj matrices </h4>

In [31]:
n = 5000
A_colmaj = np.ones((n, n), order='F') # column-major (Fortran convention)
A_rowmaj = np.ones((n, n), order='C') # row-major (C/C++ convention)




<h3> Counting Triangles (Graph) with Matrices </h3>

In [169]:
G = np.array([[0, 1, 0, 1, 0, 1],
              [1, 0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [1, 1, 1, 0, 1, 1],
              [0, 0, 0, 1, 0, 0],
              [1, 0, 0, 1, 0, 0]], dtype=int)
G

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0]])

In [193]:
def count_triangles(A):
    assert (type(A) is np.ndarray) and (A.ndim == 2) and (A.shape[0] == A.shape[1])
    TotTri=(np.matmul(A,A)*A)
    return int( np.sum(TotTri)/6)
    

In [194]:
print(count_triangles(G))

2


In [75]:
def count_triangles_proc(A):
    assert (type(A) is np.ndarray) and (A.ndim == 2) and (A.shape[0] == A.shape[1])
    print(np.matmul(A,A))
    print(np.matmul(A,A)*A)
    TotTri=(np.matmul(A,A)*A)
    return int( np.sum(TotTri)/6)    

In [76]:
count_triangles_proc(G)

[[3 1 1 2 1 1]
 [1 2 1 1 1 2]
 [1 1 1 0 1 1]
 [2 1 0 5 0 1]
 [1 1 1 0 1 1]
 [1 2 1 1 1 2]]
[[0 1 0 2 0 1]
 [1 0 0 1 0 0]
 [0 0 0 0 0 0]
 [2 1 0 0 0 1]
 [0 0 0 0 0 0]
 [1 0 0 1 0 0]]


2

In [154]:
DG={0:[2,3],1:[0,2],2:[2,3],3:[1,0]}
DG
print(" Problem:  a lot of place for ilegal graphs")

 Problem:  a lot of place for ilegal graphs


In [119]:
def getmax(DicG):
    mx=0
    for k,d in DicG.items():
        for i in d:
           if i > mx:
                mx =i
    return mx

def matrixGraph(DicG):
    '''asumes DicG is a dict fof the form {numb:[list of numbers], ..}
    converts to  n*n Adjacency Matrix  of contacts '''
    AM=np.zeros( (getmax(DicG)+1, getmax(DicG)+1) )
    for k,d in DicG.items():
        for i in d:
            AM[k,i]=1
    return AM
        

In [208]:
print(matrixGraph(DG))

[[0. 0. 1. 1.]
 [1. 0. 1. 0.]
 [0. 0. 1. 1.]
 [1. 1. 0. 0.]]


In [ ]:
DO THE SAME WITH TUPLES AS EDGES

In [188]:
a= set(  [ (1,2),(0,1),(3,2) ])

In [189]:
def getmaxS(S):
    '''assumes S a set of 2-member tuples (each one an edge between 2 nodes)'''
    mx=0

    for t in S:
        for i in t:
             if i > mx:
                mx = i
    return mx

def matrixGraphSet(SetG):
    '''asumes DicSet is a set of the form ([(tuplepairr), (tuplepair)]) ..}
    converts to  n*n Adjacency Matrix  of contacts '''
    AM=np.zeros( (getmaxS(SetG)+1, getmaxS(SetG)+1) )
    for t in SetG:
        
            AM[t]=1
            AM[t[::-1]]=1
    return AM
a=(matrixGraphSet(a))
print(a)

[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]


In [184]:
def GraphSetAM(AM):
    GS=set()
    for i in range(AM.shape[0]):
        for j in  range(i,AM.shape[1]):
            if AM[i,j]==1:
                GS|={(i,j)}
    return GS
                

In [185]:
GG=(GraphSetAM(G))
print(GG)
len(GG)

{(0, 1), (1, 3), (0, 5), (2, 3), (0, 3), (3, 4), (3, 5)}


7

In [191]:
print(a)
GSa=GraphSetAM(a)
print(GSa)

[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
{(0, 1), (2, 3), (1, 2)}


<p><span style="color:purple"> get triangles in Gb </span>

In [206]:
Gb = set({(0,1),(3,1),(2,3),(0,2),(1,2),(5,4),(4,3),(6,3),(4,6)})

In [207]:
#first go for the adjacency matrix
GbAM = matrixGraphSet(Gb)
print(GbAM)
#then count Tri
triangGb=count_triangles(GbAM)
print("num of triangles: {}".format(triangGb))

[[0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0.]]
num of triangles: 3
