<h1> Numpy </h1>

<h2> intro </h2>

In [2]:
import numpy as np
print(np.__version__)

1.14.5


$v2 \equiv \left[ \begin{matrix} 2 \\ -1.5 \end{matrix}\right]$

<h3>Creating arrays +  performace</h3>

arrayName = np.array(list)

In [4]:
myFirstAr=np.array([1,2,3,4])

In [27]:
myFirstArangeArr= np.arange(10)
myFirstArangeArr
#display_math(' \equiv '+latex_vector(myFirstAr))
#disp('First',myFirstAr)   activate HELPERS at the end

$First\equiv \left[ \begin{matrix} 1 \\ 2 \\ 3 \\ 4 \end{matrix}\right]$

 <a href='#helpers'>Link to helper function </a>

In [5]:
n=1000000
#list
L= range(n)
%timeit[i**2 for i in L]

277 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
#nparray
A=myFirstArangeArr
%timeit A**2

885 ns ± 6.01 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


$v2 \equiv \left[ \begin{matrix} 2 \\ -1.5 \end{matrix}\right]$

<h3> Multidimensional Arrays </h3>

arrayName = np.array(nestedList)

In [28]:
# Create a two-dimensional array of size 3 rows x 4 columns:
B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])

print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
print("{}  .ndim shows Dimensions".format(B.ndim))
print("{}  .shape shows Shape of n dimensions".format(B.shape))
print("{}  len(arrayName) shows 'outer' len".format(len(B)))

2  .ndim shows Dimensions
(3, 4)  .shape shows Shape of n dimensions
3  len(arrayName) shows 'outer' len


In [39]:
#join 2 matrices in a higher dim matrix
C1 = [[0, 1, 2, 3],
      [4, 5, 6, 7],
      [8, 9, 10, 11]]

C2 = [[12, 13, 14, 15],
      [16, 17, 18, 19],
      [20, 21, 22, 23]]

C = np.array([C1, C2])
print(C)
print(C.ndim)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


<h3> Routines for creating matrices/arrays </h3>

In [ ]:
print(np.zeros((3, 4)))

In [ ]:
print(np.ones((3,4)))

In [59]:
print("np.eye() uses floating-point as default")
print(np.eye(3))

np.eye() uses floating-point as default
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
print("np.diag() derives the type from its imput")
print(np.diag([1.0] * 3))
print(np.diag([x for x in range(1,4)]))  #or np.diag([1,2,3])


np.diag() derives the type from its imput
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1, 1, 1]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [55]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [56]:
A = np.empty((3, 4)) # An "empty" 3 x 4 matrix
print(A)

[[4.654042e-310 0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000 0.000000e+000]]


<h2>np methods for creating np arrays </h2>

<h3>linspace </h3>
<p> creates an e v e n l y spaced points array
    <br>
`np.linspace(start, stop, numPoints)`

In [69]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

<p> <span style='color:purple'> create an np array linspBig with the folowing start, stop and n_steps vars</span>

In [71]:
start=0
stop=1500
n_steps=6

In [84]:
#check
np.alltrue(linspBig == np.array([   0.,  300.,  600.,  900., 1200., 1500.]))

True

In [73]:
linspBig = np.linspace(start,stop,n_steps)
linspBig

array([   0.,  300.,  600.,  900., 1200., 1500.])

<h3> .arange and list comprehension  </h3>

`np.arrange(start, stop, step_size)`

In [90]:
rnge =np.arange(10,0,-2)
rnge

array([10,  8,  6,  4,  2])

In [97]:
#list comprehension
compr=np.array([x**2 for x in range(20,10,-1)])
compr

array([400, 361, 324, 289, 256, 225, 196, 169, 144, 121])

<h3>with Random Numbers</h3>

`np.random.randint(nFrom, nTo, size=(_tuple))`

In [115]:
np.random.seed=(10)
rndTen=np.random.randint(-10, 10, size=(3,4))
rndTen

array([[-1, -4,  0,  8],
       [ 6, -2, -2,  8],
       [ 3, -6, -8, -4]])

<p> <span style='color:purple'> create an np matrix twoMtr 2 by 2 with randint ranging from -6 to 7</span>

In [150]:
twoMtr= np.random.randint(-6,7,size=(2,2))
twoMtr

array([[ 3,  1],
       [ 4, -6]])

<h2> slicing and  indexing </h2>

<h2> Functions and Aggregationj </h2>

<a id='helpers' ><h2 >Helpers</h2> </a>

In [25]:
#helpers
from IPython.display import display, Math, Latex, Markdown
def display_math(str_latex):
    display(Markdown('${}$'.format(str_latex)))
def     latex_vector(v,transpose=False):
    s = r'''\left[ \begin{matrix} '''
    sep = r'''\\''' if not transpose else r''', &'''
    s += (r' {} ').format(sep).join([str(vi) for vi in v])
    s += r''' \end{matrix}\right]'''
    return s    
#represent a vector (2, -1.5)
v2 =(2,-1.5)
#latex_vector(vector((v2)))
def disp(arName,array):
    display_math(arName+'\equiv '+latex_vector(array))