<h2> neuron structure </h2>
<ul>
    <li><b>inputs</b></li>
<li><b>weights</b> - len=len(inputs)</li>
<li><b>bias   </b> - one per unique neuron</li>
    </ul>
<b> > output </b>

In [51]:
inputs = [1.2, 5.1, 2.1]
weights= [3.1, 2.1, 8.7]
bias = 3

In [49]:
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print("output: {:.2f}".format(output) )

output: 35.70


In [57]:
def print_output(inputs,weights, bias):
    output = sum( [ i*w for i,w in zip(inputs, weights) ] )+bias
    print("output: {:.2f}".format(output) )
    
def output(inputs,weights, bias):
    output = sum( [ i*w for i,w in zip(inputs, weights) ] )+bias
    #print(output)
    return output

In [56]:
output(inputs,weights, bias)

35.7

<h2> expanding to a layer </h2>

In [62]:
#another neuron with 3 inputs
print("modeling 3 neurons , a layer")
inputs = [1, 2, 3, 2.5]

weights1= [0.2 , 0.8 , -0.5 , 1 ]
weights2= [0.5 , -0.91 , 0.26 , -0.5 ]
weights3= [0.-26 , -0.27 , 0.17 , 0.87 ]

bias1 = 2
bias2 = 3
bias3= 0.5

weights = [weights1, weights2, weights3]
biases = [bias1, bias2, bias3]
#print_output(inputs,weights, bias)


modeling 3 neurons , a layer


In [63]:
def outputs_layer (inputs, weights ,  biases):
    outputs=[]
   
    for weight,bias in zip( weights,biases):
        outputs.append(output(inputs ,weight,bias  ))
    return outputs

In [64]:
outputs_layer(inputs,weights, biases)


[[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-26.0, -0.27, 0.17, 0.87]]


[4.8, 1.21, -23.354999999999997]

<h3> Shapes and numpy introduction </h3>

In [1]:
print("biases is a vector, inputs is avector")
print("weights is a matrix of vectors")

biases is a vector, inputs is avector
weights is a matrix of vectors


In [2]:
from numpy import *
#dot product
a=array([1,2,3])
b=array([3,4,5])
print('the result of dot product is a scalar')
a.dot(b)

the result of dot product is a scalar


26

In [11]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [0.2, 0.8, -0.5, 1.0]

bias =2
output = dot(inputs, weights)+ bias
print(output)

4.8


In [ ]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]


<h3>dot product of a layer </h3>
weights have to be first in the operation

In [3]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

print("weights is a matrix of vectors")
print("weights_shape:{:}".format(shape(weights)))
print("inputs_shape:{:}".format(shape(inputs)))
print("biases_shape:{:}".format(shape(biases)))

output =  dot(weights, inputs) + biases
print(output)

weights is a matrix of vectors
weights_shape:(3, 4)
inputs_shape:(4,)
biases_shape:(3,)
[4.8   1.21  2.385]


<h3> batch of inputs </h3>

adding more samples   - neurons<p>
now both <b> weights and inputs</b> will be matrices

In [1]:
import numpy as np
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0,5.0,-1.0, 2.0],
          [-1.5,2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

#we have to transpose weights' s  rows and columns, via converting to numpy array
output =  np.dot( inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


<h4>add another layer , first simple same values not object </h4>

In [2]:
import numpy as np
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0,5.0,-1.0, 2.0],
          [-1.5,2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

weights2 = [[0.1,-0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73,-0.13] ]
biases2 = [-1, 2 , -0.5 ]

layer1_outputs  = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs  = np.dot(layer1_outputs, np.array(weights2).T)+ biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


<h3> as objects </h3>

<p>X = input data to the neural network
    <p> hidden layers

In [24]:
X = [[1.0, 2.0, 3.0, 2.5],
          [2.0,5.0,-1.0, 2.0],
          [-1.5,2.7, 3.3, -0.8]]

In [6]:
#randn gaussian
np.random.randn(4,3)
0.10* np.random.randn(4,3) # scaled down


array([[-0.14722593, -0.14196407, -0.13409994],
       [ 0.08990476, -0.06666504, -0.16313144],
       [-0.00431893,  0.022263  ,  0.07600336],
       [ 0.10578044, -0.0405694 , -0.02374654]])

In [33]:
np.random.seed(0)
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):  #needed: size of input, size of neurons
        self.weights = 0.1*np.random.randn(n_inputs, n_neurons )
        self.biases = np.zeros( (1, n_neurons) ) # the first parameter is the shape
                                       
    def forward(self ,inputs):
        self.output = np.dot(inputs, self.weights)  +self.biases
    

In [38]:
layer1 = Layer_Dense(4, 5)    #num_features, num_neurons
layer2 = Layer_Dense(5, 2)#output of L1 matches input of L2
#print(layer1.weights)
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[-0.05415085  0.10895167  0.14530208  0.37564839 -0.45198362]
 [ 0.2127461  -0.37606369  1.01005301  0.67744284 -0.09021035]
 [-0.40505212  0.17924363  0.2486996  -0.03861475  0.09181559]]
[[0.06970565 0.08108632]
 [0.15274871 0.16069954]
 [0.1141027  0.00852265]]


[[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]